server:
  port: 3344

spring:
  application:
    name: lingluocloud-config #配置中心名字
  cloud:
    config:
      server:
        git:
          uri: https://github.com/littleCatBobi/springcloud-config.git
        #GitHub上面的git仓库名字
          #uri: git@github.com:littleCatBobi/springcloud-config.git